<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MSCoip.Infrastructure</RootNamespace>
    <AssemblyName>MSCoip.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.EventHubs.Processor" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Quartz.AspNetCore" />
    <PackageReference Include="Quartz.Plugins" />
    <PackageReference Include="Quartz.Serialization.Json" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Migrations\" />
  </ItemGroup>
</Project>
