#Part 1
FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS base

ARG MAJOR_MINOR=0.1
ARG PATCH=0
ARG SUFFIX_VERSION=

# Build app from sdk image
WORKDIR /src
COPY . .
RUN dotnet publish "MSCoip.sln" -c Release -o ./app /p:VersionPrefix=$MAJOR_MINOR.$PATCH /p:VersionSuffix=$SUFFIX_VERSION

#Part 2
FROM mcr.microsoft.com/dotnet/aspnet:8.0-jammy AS final

# Add library
RUN apt-get update && apt-get install -y curl

# Change timezone to local time
ENV TZ 'Asia/Jakarta'
RUN echo $TZ > /etc/timezone && \
apt-get update && apt-get install -y tzdata && \
rm /etc/localtime && \
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
dpkg-reconfigure -f noninteractive tzdata && \
apt-get clean

ENV ASPNETCORE_URLS=http://+:8080
ENV DOTNET_TieredPGO=1
ENV DOTNET_ReadyToRun=0
ENV DOTNET_TC_QuickJitForLoops=1
ENV DOTNET_EnableDiagnostics=0
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1

# Create user
RUN useradd --create-home -u 1001 ut-dad

# Copy to runtime image
ENV HOME=/home/ut-dad
WORKDIR $HOME/
COPY --from=base /src/app .

# Change to non-root privilege
USER ut-dad

EXPOSE 8080

ENTRYPOINT ["dotnet", "MSCoip.Api.dll"]
