<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>MSCoip.Api</RootNamespace>
    <AssemblyName>MSCoip.Api</AssemblyName>
    <IsWebConfigTransformDisabled>true</IsWebConfigTransformDisabled>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'Api' " />
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.AzureStorage" />
    <PackageReference Include="AspNetCore.HealthChecks.AzureServiceBus" />
    <PackageReference Include="AspNetCore.HealthChecks.Network" />
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" />
    <PackageReference Include="AspNetCore.HealthChecks.Azure.Messaging.EventHubs" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.PlatformAbstractions" />
    <PackageReference Include="NSwag.AspNetCore" />
    <PackageReference Include="ZymLabs.NSwag.FluentValidation.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Lib\*.*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.Local.json" CopyToPublishDirectory="Never" />
    <None Include="wwwroot\**">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>
</Project>
